data<-read.table("household_power_consumption.txt",header=TRUE,sep=";",dec=".")
subSetData <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
d<-paste(subSetData$Date, subSetData$Time)
datetime <- strptime(d,"%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(subSetData$Global_active_power)
subMetering1<-as.numeric(subSetData$Sub_metering_1)
subMetering2<-as.numeric(subSetData$Sub_metering_2)
subMetering3<-as.numeric(subSetData$Sub_metering_3)
voltage<-as.numeric(subSetData$Voltage)
reactive<-as.numeric(subSetData$Global_reactive_power)
png("plot4.png")
par(mfcol=c(2,2))
plot(datetime,globalActivePower,type="l",xlab="",ylab="Gloabl Active Power")
plot(datetime,subMetering1,type="l",xlab="",ylab="Energy Submetering")
lines(datetime,subMetering2,type="l",col="red")
lines(datetime,subMetering3,type="l",col="blue")
plot(datetime,voltage,type="l",xlab="datetime",ylab="Voltage")
plot(datetime,reactive,type="l",xlab="datetime",ylab="Reactive_Gloabl_Power")
dev.off()
